# Generated by Django 5.1.2 on 2024-11-26 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0003_remove_post_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='title'),
            preserve_default=False,
        ),
    ]
