# Generated by Django 5.1.2 on 2024-11-27 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0007_aboutus'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='rating',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
